name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Package Lambda Function
        run: |
          mkdir package && cp lambda_function.py package/
          cd package && zip -r ../lambda_function.zip .

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          function-name: "MyLambdaFunction"
          zip-file: "lambda_function.zip"
